//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriminalCases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CriminalCases()
        {
            this.PrisionerCases = new HashSet<PrisionerCases>();
        }
    
        public int CriminalCaseID { get; set; }
        public string CriminalCase { get; set; }
        public int JudicialCaseID { get; set; }
        public int CrimeID { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Sentence { get; set; }
        public Nullable<System.DateTime> DateMin { get; set; }
        public System.DateTime DateUpdate { get; set; }
    
        public virtual Crimes Crimes { get; set; }
        public virtual JudicialCases JudicialCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisionerCases> PrisionerCases { get; set; }
    }
}
