//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryID { get; set; }
        public int PrisonerID { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Detail { get; set; }
        public string Comment { get; set; }
    
        public virtual Prisoners Prisoners { get; set; }
    }
}
