//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class JudicialCases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JudicialCases()
        {
            this.CriminalCases = new HashSet<CriminalCases>();
        }
    
        public int JudicialCaseID { get; set; }
        public int CriminalCourtID { get; set; }
        public int DepartamentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriminalCases> CriminalCases { get; set; }
        public virtual CriminalCourts CriminalCourts { get; set; }
        public virtual Departaments Departaments { get; set; }
    }
}
