//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisionerCases
    {
        public int PrisionerCasesID { get; set; }
        public int PrisionerID { get; set; }
        public int CriminalCaseID { get; set; }
    
        public virtual CriminalCases CriminalCases { get; set; }
        public virtual Prisoners Prisoners { get; set; }
    }
}
