//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PenitentiaryContext : DbContext
    {
        public PenitentiaryContext()
            : base("name=PenitentiaryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crimes> Crimes { get; set; }
        public virtual DbSet<CriminalCases> CriminalCases { get; set; }
        public virtual DbSet<CriminalCourts> CriminalCourts { get; set; }
        public virtual DbSet<Departaments> Departaments { get; set; }
        public virtual DbSet<JudicialCases> JudicialCases { get; set; }
        public virtual DbSet<PrisionerCases> PrisionerCases { get; set; }
        public virtual DbSet<Prisoners> Prisoners { get; set; }
        public virtual DbSet<History> History { get; set; }
    }
}
